### ISSUE TITLE
Change Logstash UDP default size limit

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-udp#1]
(This issue was originally filed by @domenkozar at https://github.com/elastic/logstash/issues/2111)

---

UDP RFC relevant text:

```
A field that specifies the length in bytes of the UDP header and UDP data. The minimum length is 8 bytes since that's the length of the header. The field size sets a theoretical limit of 65,535 bytes (8 byte header + 65,527 bytes of data) for a UDP datagram. The practical limit for the data length which is imposed by the underlying IPv4 protocol is 65,507 bytes (65,535 − 8 byte UDP header − 20 byte IP header).[2]
```

I propose to raise the default limit of UDP buffer to 65,507 bytes.

**Comment by DanFelton** [comment]
Obviously last time this change was not made, but as time goes on and data will inevitably always increase in volume, it seems prudent to make this change as suggested.
