### ISSUE TITLE
bad read performance since shutdown refactor

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-udp#21]
From my experiments today, using IO.select + nonblocking rcvm_from makes the plugin half as fast as before. In my machine I can see around 17keps with nonblocking io, but 40keps with a blocking read.

The difference is:

#### slower

```ruby
   while !stop?
      next if IO.select([@udp], [], [], 0.5).nil?
      payload, client = @udp.recvfrom_nonblock(@buffer_size)
      next if payload.empty?
      @input_to_worker.push([payload, client])
    end
```

#### faster

```ruby
   while !stop?
      payload, client = @udp.recvfrom(@buffer_size)
      @input_to_worker.push([payload, client])
    end
```

The obvious downside is that the faster solution makes the plugin non interruptible if no data is coming, since recvfrom is blocking..thoughts?

**Comment by IrlJidel** [comment]
I'm seeing the same issue - '[main]<udp' cpu usage is 6x using select/recvfrom_nonblock

I applied a hack to reduce the number of select calls

When sending 15K msgs/sec to UDP listener:

non blocking:   63.1%  [main]<udp
blocking: 11.0%  [main]<udp
hack: 18.6% [main]<udp

```ruby
    while !stop?
      next if IO.select([@udp], [], [], 0.5).nil?
      #collect datagram message and add to queue
      @queue_size.times {
        begin
          payload, client = @udp.recvfrom_nonblock(@buffer_size)
          next if payload.empty?
          @input_to_worker.push([payload, client])
        rescue IO::EAGAINWaitReadable
          break
        end
      }
    end
```

**Comment by IrlJidel** [comment]
@jsvd any comment re  my approach? A 2-3x reduction in throughput in quite a significant performance regression.

**Comment by jsvd** [comment]
Can you format that as a pull request so we can merge it? :)

**Comment by IrlJidel** [comment]
Can this be closed now?

**Comment by jsvd** [comment]
yes, thanks again for your contribution
