### ISSUE TITLE
Move the `host` field to a location in line with ECS or make it configurable

### ISSUE THREAD

**Issue by webmat** [logstash-plugins/logstash-input-udp#42]
This is related to #40, but not quite the same request.

Please move the `host` to `destination.ip`, to be better aligned with ECS and to avoid clashing with `host` being an object in more and more situations (including, but not limited to ECS).

If that's a no-go, perhaps a first step would be to make the destination field for this information configurable?

**Comment by praseodym** [comment]
The correct ECS field would be `source.ip`, but I think moving all input-provided fields under `[@metadata]` makes more sense. This is also more in line with plugins like [logstash-input-kafka](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#_metadata_fields) and [logstash-input-rabbitmq](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-rabbitmq.html#_description_29).

**Comment by webmat** [comment]
Yes I could go with that. My goal here is mainly to avoid the clash with ECS `host` object.

source v dest: I read that as being the same host as the host:port being listened on. Makes more sense if it's the counterparty's IP address, indeed :-)

**Comment by jsvd** [comment]
> If that's a no-go, perhaps a first step would be to make the destination field for this information configurable?

I'm ++ on having this configurable with the current value as default. If we break this with a new default, we'll have to maintain two major versions of this plugin for quite some time and also that version will only ship with logstash by default by 7.0.0

**Comment by praseodym** [comment]
I'll open a PR.
