### ISSUE TITLE
Implement ECS-Compatibility Mode

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-input-udp#48]
_This is a stub issue, and needs to be fleshed out with details specific to
this plugin._

***

As a part of the effort to make plugins able to run in an ECS-Compatible manner
by default in an upcoming release of Logstash, this plugin needs to either
implement an ECS-Compatibility mode or certify that it does not implicitly use
fields that conflict with ECS.

**Comment by andsel** [comment]
The only field added is the one the user selects with `source_ip_fieldname` which is `host` by default. The plugin extract the source IP and set that field is not yet present: https://github.com/logstash-plugins/logstash-input-udp/blob/b0833dda60c1d9f9a223fc8a61bf026e765bad29/lib/logstash/inputs/udp.rb#L177
If the user customize the name is out of control of ECS but if the user leverage the default behaviour and has ecs_compatibility enabled we should switch that field to a new name `[host][ip]`. This rename could happen at `register` time
